### PR TITLE
Update Technical Master Plan

### PR DESCRIPTION
**Pull request by jcstine**
Intention:  1) eliminate redundancies; 2) bring statements of OVN vision, mission, and objectives up to date with Fall 2000 Steering Committee decisions; 3) align research on prior standards to Master Plan sections on critical OVN components.  A tighter, stronger document to start the new year, suitable for viewing by prospective sponsors.

### CODE REVIEW

**Comment by oitacoleman** [comment]
@oitacoleman approves this pull request #111

**Review by Jim1151 — APPROVED** [review]

**Review by lawrencelin96 — APPROVED** [review]

**Review by MirkoSaul — APPROVED** [review]

**Comment by jcstine** [comment]
Reviewed, corrected conflicts within JCStine-patch-7 branch pull request to Master Plan.  Believe all is set to go.

**Comment by maridob** [comment]
Hi @jcstine - you can now merge this.

**Comment by jcstine** [comment]
Merged as of 2021.01.22 per Maridob

**Pull request merged**
