### PR TITLE
Update vocabulary.md

### PR DESCRIPTION
**Pull request by jcstine**
First of two additions of vocabulary and definitions from the 2020.12.18 OVN Vocabulary Reconciliation session.

### CODE REVIEW

**Review by Jim1151 — APPROVED** [review]

**Review by pmotch — APPROVED** [review]
LGTM formatting wise (I assume Jim's approval was for the content).

**Comment by pmotch** [comment]
Given there is an approval, @jcstine you can merge this PR now.

**Comment by maridob** [comment]
Hi @jcstine - do you want to merge the changes if this is approved?

**Comment by jcstine** [comment]
Merging #105 with Vocabulary.md

**Pull request merged**
